[development]
port = 8000
address = "127.0.0.1"
log = "normal"

[production]
port = 8000
address = "0.0.0.0"
log = "critical"

[global]
secret_key = "your_secret_key"  # Replace with your own secret key
